### ISSUE TITLE
sample configurations for Authority are wrong

### ISSUE THREAD

**Issue by NullByteSuiteDevs** [katzenpost/daemons#14]
I've been attempting to set up a Katzenpost mixnet according to the instructions listed [here](https://katzenpost.mixnetworks.org/docs/setup.html). I am at the point of setting up the PKI. So I wget the sample configuration file and edit the Authority address and DataDir. When I try to run the nonvoting binary with the -g flag to generate a key, I am given this error:

`Failed to load config file 'authority.toml': config: Undecoded keys in config file: [Parameters.SendShift]`

I have found [this commit](https://github.com/katzenpost/authority/commit/8c19aabf5ae3f5e624d603805322d5bd0fa0fa9b#diff-e07ea7b930ae51f9ecb0a5a3be2f333e) that added this, but I am confused as to what the undecoded keys could be. I downloaded the sample configuration and edited it as stated on katzenpost.mixnetworks.org

I can provide more debugging information as needed. I'm not very well versed in Go.

**Comment by david415** [comment]
This is a documentation bug and not a bug with our software.

There are no parameters with the word "shift" in the name anymore. I removed them all.
Therefor your configuration file is incorrect... AND our docs must also be incorrect.

**Comment by mixmasala** [comment]
I've removed the SendShift parameter from the config example.
Note that if you want to set up a test mixnet (on local loopback addresses) I wrote a tool to generate the configuration files:
https://github.com/katzenpost/tools/tree/master/genconfig
